var pokemon_evs = [
	{"id": "1", "name": "Bulbasaur", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "2", "name": "Ivysaur", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "1", "spe": "0"},
	{"id": "3", "name": "Venusaur", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "1", "spe": "0"},
	{"id": "3M", "name": "Venusaur (Mega Venusaur)", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "1", "spe": "0"},
	{"id": "4", "name": "Charmander", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "5", "name": "Charmeleon", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "6", "name": "Charizard", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "6MX", "name": "Charizard (Mega Charizard X)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "6MY", "name": "Charizard (Mega Charizard Y)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "7", "name": "Squirtle", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "8", "name": "Wartortle", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "9", "name": "Blastoise", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "9M", "name": "Blastoise (Mega Blastoise)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "10", "name": "Caterpie", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "11", "name": "Metapod", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "12", "name": "Butterfree", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "1", "spe": "0"},
	{"id": "13", "name": "Weedle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "14", "name": "Kakuna", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "15", "name": "Beedrill", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "15M", "name": "Beedrill (Mega Beedrill)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "16", "name": "Pidgey", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "17", "name": "Pidgeotto", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "18", "name": "Pidgeot", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "18M", "name": "Pidgeot (Mega Pidgeot)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "19", "name": "Rattata", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "20", "name": "Raticate", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "21", "name": "Spearow", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "22", "name": "Fearow", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "23", "name": "Ekans", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "24", "name": "Arbok", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "25", "name": "Pikachu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "26", "name": "Raichu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "27", "name": "Sandshrew", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "28", "name": "Sandslash", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "29", "name": "Nidoran♀", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "30", "name": "Nidorina", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "31", "name": "Nidoqueen", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "32", "name": "Nidoran♂", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "33", "name": "Nidorino", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "34", "name": "Nidoking", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "35", "name": "Clefairy", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "36", "name": "Clefable", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "37", "name": "Vulpix", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "38", "name": "Ninetales", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "1"},
	{"id": "38A", "name": "Ninetales (Alola Form)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "39", "name": "Jigglypuff", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "40", "name": "Wigglytuff", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "41", "name": "Zubat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "42", "name": "Golbat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "43", "name": "Oddish", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "44", "name": "Gloom", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "45", "name": "Vileplume", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "46", "name": "Paras", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "47", "name": "Parasect", "hp": "0", "atk": "2", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "48", "name": "Venonat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "49", "name": "Venomoth", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "50", "name": "Diglett", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "51", "name": "Dugtrio", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "51A", "name": "Dugtrio (Alola Form)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "52", "name": "Meowth", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "53", "name": "Persian", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "54", "name": "Psyduck", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "55", "name": "Golduck", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "56", "name": "Mankey", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "57", "name": "Primeape", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "58", "name": "Growlithe", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "59", "name": "Arcanine", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "60", "name": "Poliwag", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "61", "name": "Poliwhirl", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "62", "name": "Poliwrath", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "63", "name": "Abra", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "64", "name": "Kadabra", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "65", "name": "Alakazam", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "65M", "name": "Alakazam (Mega Alakazam)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "66", "name": "Machop", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "67", "name": "Machoke", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "68", "name": "Machamp", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "69", "name": "Bellsprout", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "70", "name": "Weepinbell", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "71", "name": "Victreebel", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "72", "name": "Tentacool", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "73", "name": "Tentacruel", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "74", "name": "Geodude", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "75", "name": "Graveler", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "76", "name": "Golem", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "77", "name": "Ponyta", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "78", "name": "Rapidash", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "79", "name": "Slowpoke", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "80", "name": "Slowbro", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "80M", "name": "Slowbro (Mega Slowbro)", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "81", "name": "Magnemite", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "82", "name": "Magneton", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "83", "name": "Farfetch'd", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "84", "name": "Doduo", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "85", "name": "Dodrio", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "86", "name": "Seel", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "87", "name": "Dewgong", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "88", "name": "Grimer", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "89", "name": "Muk", "hp": "1", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "90", "name": "Shellder", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "91", "name": "Cloyster", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "92", "name": "Gastly", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "93", "name": "Haunter", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "94", "name": "Gengar", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "94M", "name": "Gengar (Mega Gengar)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "95", "name": "Onix", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "96", "name": "Drowzee", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "97", "name": "Hypno", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "98", "name": "Krabby", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "99", "name": "Kingler", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "100", "name": "Voltorb", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "101", "name": "Electrode", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "102", "name": "Exeggcute", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "103", "name": "Exeggutor", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "104", "name": "Cubone", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "105", "name": "Marowak", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "106", "name": "Hitmonlee", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "107", "name": "Hitmonchan", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "108", "name": "Lickitung", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "109", "name": "Koffing", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "110", "name": "Weezing", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "111", "name": "Rhyhorn", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "112", "name": "Rhydon", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "113", "name": "Chansey", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "114", "name": "Tangela", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "115", "name": "Kangaskhan", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "115M", "name": "Kangaskhan (Mega Kangaskhan)", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "116", "name": "Horsea", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "117", "name": "Seadra", "hp": "0", "atk": "0", "def": "1", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "118", "name": "Goldeen", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "119", "name": "Seaking", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "120", "name": "Staryu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "121", "name": "Starmie", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "122", "name": "Mr. Mime", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "123", "name": "Scyther", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "124", "name": "Jynx", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "125", "name": "Electabuzz", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "126", "name": "Magmar", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "127", "name": "Pinsir", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "127M", "name": "Pinsir (Mega Pinsir)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "128", "name": "Tauros", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "129", "name": "Magikarp", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "130", "name": "Gyarados", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "130M", "name": "Gyarados (Mega Gyarados)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "131", "name": "Lapras", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "132", "name": "Ditto", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "133", "name": "Eevee", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "134", "name": "Vaporeon", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "135", "name": "Jolteon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "136", "name": "Flareon", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "137", "name": "Porygon", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "138", "name": "Omanyte", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "139", "name": "Omastar", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "140", "name": "Kabuto", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "141", "name": "Kabutops", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "142", "name": "Aerodactyl", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "142M", "name": "Aerodactyl (Mega Aerodactyl)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "143", "name": "Snorlax", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "144", "name": "Articuno", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "145", "name": "Zapdos", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "146", "name": "Moltres", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "147", "name": "Dratini", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "148", "name": "Dragonair", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "149", "name": "Dragonite", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "150", "name": "Mewtwo", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "150MX", "name": "Mewtwo (Mega Mewtwo X)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "150MY", "name": "Mewtwo (Mega Mewtwo Y)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "151", "name": "Mew", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "152", "name": "Chikorita", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "153", "name": "Bayleef", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "154", "name": "Meganium", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "155", "name": "Cyndaquil", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "156", "name": "Quilava", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "157", "name": "Typhlosion", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "158", "name": "Totodile", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "159", "name": "Croconaw", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "160", "name": "Feraligatr", "hp": "0", "atk": "2", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "161", "name": "Sentret", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "162", "name": "Furret", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "163", "name": "Hoothoot", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "164", "name": "Noctowl", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "165", "name": "Ledyba", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "166", "name": "Ledian", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "167", "name": "Spinarak", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "168", "name": "Ariados", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "169", "name": "Crobat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "170", "name": "Chinchou", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "171", "name": "Lanturn", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "172", "name": "Pichu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "173", "name": "Cleffa", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "174", "name": "Igglybuff", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "175", "name": "Togepi", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "176", "name": "Togetic", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "177", "name": "Natu", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "178", "name": "Xatu", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "179", "name": "Mareep", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "180", "name": "Flaaffy", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "181", "name": "Ampharos", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "181M", "name": "Ampharos (Mega Ampharos)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "182", "name": "Bellossom", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "183", "name": "Marill", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "184", "name": "Azumarill", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "185", "name": "Sudowoodo", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "186", "name": "Politoed", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "187", "name": "Hoppip", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "188", "name": "Skiploom", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "189", "name": "Jumpluff", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "190", "name": "Aipom", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "191", "name": "Sunkern", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "192", "name": "Sunflora", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "193", "name": "Yanma", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "194", "name": "Wooper", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "195", "name": "Quagsire", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "196", "name": "Espeon", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "197", "name": "Umbreon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "198", "name": "Murkrow", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "199", "name": "Slowking", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "200", "name": "Misdreavus", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "201", "name": "Unown", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "202", "name": "Wobbuffet", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "203", "name": "Girafarig", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "204", "name": "Pineco", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "205", "name": "Forretress", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "206", "name": "Dunsparce", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "207", "name": "Gligar", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "208", "name": "Steelix", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "208M", "name": "Steelix (Mega Steelix)", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "209", "name": "Snubbull", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "210", "name": "Granbull", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "211", "name": "Qwilfish", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "212", "name": "Scizor", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "212M", "name": "Scizor (Mega Scizor)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "213", "name": "Shuckle", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "214", "name": "Heracross", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "214M", "name": "Heracross (Mega Heracross)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "215", "name": "Sneasel", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "216", "name": "Teddiursa", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "217", "name": "Ursaring", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "218", "name": "Slugma", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "219", "name": "Magcargo", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "220", "name": "Swinub", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "221", "name": "Piloswine", "hp": "1", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "222", "name": "Corsola", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "223", "name": "Remoraid", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "224", "name": "Octillery", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "225", "name": "Delibird", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "226", "name": "Mantine", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "227", "name": "Skarmory", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "228", "name": "Houndour", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "229", "name": "Houndoom", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "229M", "name": "Houndoom (Mega Houndoom)", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "230", "name": "Kingdra", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "1", "spe": "0"},
	{"id": "231", "name": "Phanpy", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "232", "name": "Donphan", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "233", "name": "Porygon2", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "234", "name": "Stantler", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "235", "name": "Smeargle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "236", "name": "Tyrogue", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "237", "name": "Hitmontop", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "238", "name": "Smoochum", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "239", "name": "Elekid", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "240", "name": "Magby", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "241", "name": "Miltank", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "242", "name": "Blissey", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "243", "name": "Raikou", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "2"},
	{"id": "244", "name": "Entei", "hp": "1", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "245", "name": "Suicune", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "246", "name": "Larvitar", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "247", "name": "Pupitar", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "248", "name": "Tyranitar", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "248M", "name": "Tyranitar (Mega Tyranitar)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "249", "name": "Lugia", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "250", "name": "Ho-Oh", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "251", "name": "Celebi", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "252", "name": "Treecko", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "253", "name": "Grovyle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "254", "name": "Sceptile", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "254M", "name": "Sceptile (Mega Sceptile)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "255", "name": "Torchic", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "256", "name": "Combusken", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "257", "name": "Blaziken", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "257M", "name": "Blaziken (Mega Blaziken)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "258", "name": "Mudkip", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "259", "name": "Marshtomp", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "260", "name": "Swampert", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "260M", "name": "Swampert (Mega Swampert)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "261", "name": "Poochyena", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "262", "name": "Mightyena", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "263", "name": "Zigzagoon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "264", "name": "Linoone", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "265", "name": "Wurmple", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "266", "name": "Silcoon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "267", "name": "Beautifly", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "268", "name": "Cascoon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "269", "name": "Dustox", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "270", "name": "Lotad", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "271", "name": "Lombre", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "272", "name": "Ludicolo", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "273", "name": "Seedot", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "274", "name": "Nuzleaf", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "275", "name": "Shiftry", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "276", "name": "Taillow", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "277", "name": "Swellow", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "278", "name": "Wingull", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "279", "name": "Pelipper", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "280", "name": "Ralts", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "281", "name": "Kirlia", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "282", "name": "Gardevoir", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "282M", "name": "Gardevoir (Mega Gardevoir)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "283", "name": "Surskit", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "284", "name": "Masquerain", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "1", "spe": "0"},
	{"id": "285", "name": "Shroomish", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "286", "name": "Breloom", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "287", "name": "Slakoth", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "288", "name": "Vigoroth", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "289", "name": "Slaking", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "290", "name": "Nincada", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "291", "name": "Ninjask", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "292", "name": "Shedinja", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "293", "name": "Whismur", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "294", "name": "Loudred", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "295", "name": "Exploud", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "296", "name": "Makuhita", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "297", "name": "Hariyama", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "298", "name": "Azurill", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "299", "name": "Nosepass", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "300", "name": "Skitty", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "301", "name": "Delcatty", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "302", "name": "Sableye", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "302M", "name": "Sableye (Mega Sableye)", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "303", "name": "Mawile", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "303M", "name": "Mawile (Mega Mawile)", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "304", "name": "Aron", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "305", "name": "Lairon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "306", "name": "Aggron", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "306M", "name": "Aggron (Mega Aggron)", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "307", "name": "Meditite", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "308", "name": "Medicham", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "308M", "name": "Medicham (Mega Medicham)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "309", "name": "Electrike", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "310", "name": "Manectric", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "310M", "name": "Manectric (Mega Manectric)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "311", "name": "Plusle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "312", "name": "Minun", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "313", "name": "Volbeat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "314", "name": "Illumise", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "315", "name": "Roselia", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "316", "name": "Gulpin", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "317", "name": "Swalot", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "318", "name": "Carvanha", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "319", "name": "Sharpedo", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "319M", "name": "Sharpedo (Mega Sharpedo)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "320", "name": "Wailmer", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "321", "name": "Wailord", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "322", "name": "Numel", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "323", "name": "Camerupt", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "323M", "name": "Camerupt (Mega Camerupt)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "324", "name": "Torkoal", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "325", "name": "Spoink", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "326", "name": "Grumpig", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "327", "name": "Spinda", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "328", "name": "Trapinch", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "329", "name": "Vibrava", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "330", "name": "Flygon", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "331", "name": "Cacnea", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "332", "name": "Cacturne", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "333", "name": "Swablu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "334", "name": "Altaria", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "334M", "name": "Altaria (Mega Altaria)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "335", "name": "Zangoose", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "336", "name": "Seviper", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "337", "name": "Lunatone", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "338", "name": "Solrock", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "339", "name": "Barboach", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "340", "name": "Whiscash", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "341", "name": "Corphish", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "342", "name": "Crawdaunt", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "343", "name": "Baltoy", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "344", "name": "Claydol", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "345", "name": "Lileep", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "346", "name": "Cradily", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "347", "name": "Anorith", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "348", "name": "Armaldo", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "349", "name": "Feebas", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "350", "name": "Milotic", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "351", "name": "Castform", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "352", "name": "Kecleon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "353", "name": "Shuppet", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "354", "name": "Banette", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "354M", "name": "Banette (Mega Banette)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "355", "name": "Duskull", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "356", "name": "Dusclops", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "357", "name": "Tropius", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "358", "name": "Chimecho", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "1", "spe": "0"},
	{"id": "359", "name": "Absol", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "359M", "name": "Absol (Mega Absol)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "360", "name": "Wynaut", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "361", "name": "Snorunt", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "362", "name": "Glalie", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "362M", "name": "Glalie (Mega Glalie)", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "363", "name": "Spheal", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "364", "name": "Sealeo", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "365", "name": "Walrein", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "366", "name": "Clamperl", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "367", "name": "Huntail", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "368", "name": "Gorebyss", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "369", "name": "Relicanth", "hp": "1", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "370", "name": "Luvdisc", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "371", "name": "Bagon", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "372", "name": "Shelgon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "373", "name": "Salamence", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "373M", "name": "Salamence (Mega Salamence)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "374", "name": "Beldum", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "375", "name": "Metang", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "376", "name": "Metagross", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "376M", "name": "Metagross (Mega Metagross)", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "377", "name": "Regirock", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "378", "name": "Regice", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "379", "name": "Registeel", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "380", "name": "Latias", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "380M", "name": "Latias (Mega Latias)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "381", "name": "Latios", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "381M", "name": "Latios (Mega Latios)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "382", "name": "Kyogre", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "382P", "name": "Kyogre (Primal Reversion)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "383", "name": "Groudon", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "383P", "name": "Groudon (Primal Reversion)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "384", "name": "Rayquaza", "hp": "0", "atk": "2", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "384M", "name": "Rayquaza (Mega Rayquaza)", "hp": "0", "atk": "2", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "385", "name": "Jirachi", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "386", "name": "Deoxys (Normal Forme)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "386", "name": "Deoxys (Attack Forme)", "hp": "0", "atk": "2", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "386", "name": "Deoxys (Defense Forme)", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "386", "name": "Deoxys (Speed Forme)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "387", "name": "Turtwig", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "388", "name": "Grotle", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "389", "name": "Torterra", "hp": "0", "atk": "2", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "390", "name": "Chimchar", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "391", "name": "Monferno", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "392", "name": "Infernape", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "393", "name": "Piplup", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "394", "name": "Prinplup", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "395", "name": "Empoleon", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "396", "name": "Starly", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "397", "name": "Staravia", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "398", "name": "Staraptor", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "399", "name": "Bidoof", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "400", "name": "Bibarel", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "401", "name": "Kricketot", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "402", "name": "Kricketune", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "403", "name": "Shinx", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "404", "name": "Luxio", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "405", "name": "Luxray", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "406", "name": "Budew", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "407", "name": "Roserade", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "408", "name": "Cranidos", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "409", "name": "Rampardos", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "410", "name": "Shieldon", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "411", "name": "Bastiodon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "412", "name": "Burmy", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "413", "name": "Wormadam (Plant Cloak)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "413", "name": "Wormadam (Sandy Cloak)", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "413", "name": "Wormadam (Trash Cloak)", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "414", "name": "Mothim", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "415", "name": "Combee", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "416", "name": "Vespiquen", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "417", "name": "Pachirisu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "418", "name": "Buizel", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "419", "name": "Floatzel", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "420", "name": "Cherubi", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "421", "name": "Cherrim", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "422", "name": "Shellos", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "423", "name": "Gastrodon", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "424", "name": "Ambipom", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "425", "name": "Drifloon", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "426", "name": "Drifblim", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "427", "name": "Buneary", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "428", "name": "Lopunny", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "428M", "name": "Lopunny (Mega Lopunny)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "429", "name": "Mismagius", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "1", "spe": "0"},
	{"id": "430", "name": "Honchkrow", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "431", "name": "Glameow", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "432", "name": "Purugly", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "433", "name": "Chingling", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "434", "name": "Stunky", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "435", "name": "Skuntank", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "436", "name": "Bronzor", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "437", "name": "Bronzong", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "438", "name": "Bonsly", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "439", "name": "Mime Jr.", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "440", "name": "Happiny", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "441", "name": "Chatot", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "442", "name": "Spiritomb", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "443", "name": "Gible", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "444", "name": "Gabite", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "445", "name": "Garchomp", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "445M", "name": "Garchomp (Mega Garchomp)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "446", "name": "Munchlax", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "447", "name": "Riolu", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "448", "name": "Lucario", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "448M", "name": "Lucario (Mega Lucario)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "449", "name": "Hippopotas", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "450", "name": "Hippowdon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "451", "name": "Skorupi", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "452", "name": "Drapion", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "453", "name": "Croagunk", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "454", "name": "Toxicroak", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "455", "name": "Carnivine", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "456", "name": "Finneon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "457", "name": "Lumineon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "458", "name": "Mantyke", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "459", "name": "Snover", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "460", "name": "Abomasnow", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "460M", "name": "Abomasnow (Mega Abomasnow)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "461", "name": "Weavile", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "462", "name": "Magnezone", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "463", "name": "Lickilicky", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "464", "name": "Rhyperior", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "465", "name": "Tangrowth", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "466", "name": "Electivire", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "467", "name": "Magmortar", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "468", "name": "Togekiss", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "1", "spe": "0"},
	{"id": "469", "name": "Yanmega", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "470", "name": "Leafeon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "471", "name": "Glaceon", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "472", "name": "Gliscor", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "473", "name": "Mamoswine", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "474", "name": "Porygon-Z", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "475", "name": "Gallade", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "475M", "name": "Gallade (Mega Gallade)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "476", "name": "Probopass", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "477", "name": "Dusknoir", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "478", "name": "Froslass", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "479", "name": "Rotom (Normal Rotom)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "479", "name": "Rotom (Heat Rotom)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "479", "name": "Rotom (Wash Rotom)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "479", "name": "Rotom (Frost Rotom)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "479", "name": "Rotom (Fan Rotom)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "479", "name": "Rotom (Mow Rotom)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "480", "name": "Uxie", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "481", "name": "Mesprit", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "1", "spe": "0"},
	{"id": "482", "name": "Azelf", "hp": "0", "atk": "2", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "483", "name": "Dialga", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "484", "name": "Palkia", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "485", "name": "Heatran", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "486", "name": "Regigigas", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "487", "name": "Giratina", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "488", "name": "Cresselia", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "489", "name": "Phione", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "490", "name": "Manaphy", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "491", "name": "Darkrai", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "1"},
	{"id": "492", "name": "Shaymin (Land Forme)", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "492", "name": "Shaymin (Sky Forme)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "493", "name": "Arceus", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "494", "name": "Victini", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "495", "name": "Snivy", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "496", "name": "Servine", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "497", "name": "Serperior", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "498", "name": "Tepig", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "499", "name": "Pignite", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "500", "name": "Emboar", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "501", "name": "Oshawott", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "502", "name": "Dewott", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "503", "name": "Samurott", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "504", "name": "Patrat", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "505", "name": "Watchog", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "506", "name": "Lillipup", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "507", "name": "Herdier", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "508", "name": "Stoutland", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "509", "name": "Purrloin", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "510", "name": "Liepard", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "511", "name": "Pansage", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "512", "name": "Simisage", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "513", "name": "Pansear", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "514", "name": "Simisear", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "515", "name": "Panpour", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "516", "name": "Simipour", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "517", "name": "Munna", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "518", "name": "Musharna", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "519", "name": "Pidove", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "520", "name": "Tranquill", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "521", "name": "Unfezant", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "522", "name": "Blitzle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "523", "name": "Zebstrika", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "524", "name": "Roggenrola", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "525", "name": "Boldore", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "526", "name": "Gigalith", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "527", "name": "Woobat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "528", "name": "Swoobat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "529", "name": "Drilbur", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "530", "name": "Excadrill", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "531", "name": "Audino", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "531M", "name": "Audino (Mega Audino)", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "532", "name": "Timburr", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "533", "name": "Gurdurr", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "534", "name": "Conkeldurr", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "535", "name": "Tympole", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "536", "name": "Palpitoad", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "537", "name": "Seismitoad", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "538", "name": "Throh", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "539", "name": "Sawk", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "540", "name": "Sewaddle", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "541", "name": "Swadloon", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "542", "name": "Leavanny", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "543", "name": "Venipede", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "544", "name": "Whirlipede", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "545", "name": "Scolipede", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "546", "name": "Cottonee", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "547", "name": "Whimsicott", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "548", "name": "Petilil", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "549", "name": "Lilligant", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "550", "name": "Basculin", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "551", "name": "Sandile", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "552", "name": "Krokorok", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "553", "name": "Krookodile", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "554", "name": "Darumaka", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "555", "name": "Darmanitan (Standard Mode)", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "555", "name": "Darmanitan (Zen Mode)", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "556", "name": "Maractus", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "557", "name": "Dwebble", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "558", "name": "Crustle", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "559", "name": "Scraggy", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "560", "name": "Scrafty", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "561", "name": "Sigilyph", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "562", "name": "Yamask", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "563", "name": "Cofagrigus", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "564", "name": "Tirtouga", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "565", "name": "Carracosta", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "566", "name": "Archen", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "567", "name": "Archeops", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "568", "name": "Trubbish", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "569", "name": "Garbodor", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "570", "name": "Zorua", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "571", "name": "Zoroark", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "572", "name": "Minccino", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "573", "name": "Cinccino", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "574", "name": "Gothita", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "575", "name": "Gothorita", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "576", "name": "Gothitelle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "577", "name": "Solosis", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "578", "name": "Duosion", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "579", "name": "Reuniclus", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "580", "name": "Ducklett", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "581", "name": "Swanna", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "582", "name": "Vanillite", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "583", "name": "Vanillish", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "584", "name": "Vanilluxe", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "585", "name": "Deerling", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "586", "name": "Sawsbuck", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "587", "name": "Emolga", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "588", "name": "Karrablast", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "589", "name": "Escavalier", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "590", "name": "Foongus", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "591", "name": "Amoonguss", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "592", "name": "Frillish", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "593", "name": "Jellicent", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "594", "name": "Alomomola", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "595", "name": "Joltik", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "596", "name": "Galvantula", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "597", "name": "Ferroseed", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "598", "name": "Ferrothorn", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "599", "name": "Klink", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "600", "name": "Klang", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "601", "name": "Klinklang", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "602", "name": "Tynamo", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "603", "name": "Eelektrik", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "604", "name": "Eelektross", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "605", "name": "Elgyem", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "606", "name": "Beheeyem", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "607", "name": "Litwick", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "608", "name": "Lampent", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "609", "name": "Chandelure", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "610", "name": "Axew", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "611", "name": "Fraxure", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "612", "name": "Haxorus", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "613", "name": "Cubchoo", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "614", "name": "Beartic", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "615", "name": "Cryogonal", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "616", "name": "Shelmet", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "617", "name": "Accelgor", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "618", "name": "Stunfisk", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "619", "name": "Mienfoo", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "620", "name": "Mienshao", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "621", "name": "Druddigon", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "622", "name": "Golett", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "623", "name": "Golurk", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "624", "name": "Pawniard", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "625", "name": "Bisharp", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "626", "name": "Bouffalant", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "627", "name": "Rufflet", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "628", "name": "Braviary", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "629", "name": "Vullaby", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "630", "name": "Mandibuzz", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "631", "name": "Heatmor", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "632", "name": "Durant", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "633", "name": "Deino", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "634", "name": "Zweilous", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "635", "name": "Hydreigon", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "636", "name": "Larvesta", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "637", "name": "Volcarona", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "638", "name": "Cobalion", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "639", "name": "Terrakion", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "640", "name": "Virizion", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "641", "name": "Tornadus (Incarnate Forme)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "641", "name": "Tornadus (Therian Forme)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "642", "name": "Thundurus (Incarnate Forme)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "642", "name": "Thundurus (Therian Forme)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "643", "name": "Reshiram", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "644", "name": "Zekrom", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "645", "name": "Landorus (Incarnate Forme)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "645", "name": "Landorus (Therian Forme)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "646", "name": "Kyurem", "hp": "1", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "646", "name": "Kyurem (White Kyurem)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "646", "name": "Kyurem (Black Kyurem)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "647", "name": "Keldeo", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "648", "name": "Meloetta (Aria Forme)", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "1", "spe": "1"},
	{"id": "648", "name": "Meloetta (Pirouette Forme)", "hp": "0", "atk": "1", "def": "1", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "649", "name": "Genesect", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "650", "name": "Chespin", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "651", "name": "Quilladin", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "652", "name": "Chesnaught", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "653", "name": "Fennekin", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "654", "name": "Braixen", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "655", "name": "Delphox", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "656", "name": "Froakie", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "657", "name": "Frogadier", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "658", "name": "Greninja", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "658A", "name": "Greninja (Ash-Greninja Form)", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "659", "name": "Bunnelby", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "660", "name": "Diggersby", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "661", "name": "Fletchling", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "662", "name": "Fletchinder", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "663", "name": "Talonflame", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "664", "name": "Scatterbug", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "665", "name": "Spewpa", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "666", "name": "Vivillon", "hp": "1", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "667", "name": "Litleo", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "668", "name": "Pyroar", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "669", "name": "Flabébé", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "670", "name": "Floette", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "671", "name": "Florges", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "672", "name": "Skiddo", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "673", "name": "Gogoat", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "674", "name": "Pancham", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "675", "name": "Pangoro", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "676", "name": "Furfrou", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "677", "name": "Espurr", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "678", "name": "Meowstic", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "679", "name": "Honedge", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "680", "name": "Doublade", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "681", "name": "Aegislash (Shield Forme)", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "681B", "name": "Aegislash (Blade Forme)", "hp": "0", "atk": "2", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "682", "name": "Spritzee", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "683", "name": "Aromatisse", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "684", "name": "Swirlix", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "685", "name": "Slurpuff", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "686", "name": "Inkay", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "687", "name": "Malamar", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "688", "name": "Binacle", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "689", "name": "Barbaracle", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "690", "name": "Skrelp", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "691", "name": "Dragalge", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "692", "name": "Clauncher", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "693", "name": "Clawitzer", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "694", "name": "Helioptile", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "695", "name": "Heliolisk", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "696", "name": "Tyrunt", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "697", "name": "Tyrantrum", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "698", "name": "Amaura", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "699", "name": "Aurorus", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "700", "name": "Sylveon", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "701", "name": "Hawlucha", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "702", "name": "Dedenne", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "703", "name": "Carbink", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "704", "name": "Goomy", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "705", "name": "Sliggoo", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "706", "name": "Goodra", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "707", "name": "Klefki", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "708", "name": "Phantump", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "709", "name": "Trevenant", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "710", "name": "Pumpkaboo", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "711", "name": "Gourgeist", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "712", "name": "Bergmite", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "713", "name": "Avalugg", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "714", "name": "Noibat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "715", "name": "Noivern", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "716", "name": "Xerneas", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "717", "name": "Yveltal", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "718", "name": "Zygarde (50% Forme)", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "718T", "name": "Zygarde (10% Forme)", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "718C", "name": "Zygarde (Complete Forme)", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "719", "name": "Diancie", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "719M", "name": "Diancie (Mega Diancie)", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "720", "name": "Hoopa", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "720U", "name": "Hoopa (Hoopa Unbound)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "721", "name": "Volcanion", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "722", "name": "Rowlet", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "723", "name": "Dartrix", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "724", "name": "Decidueye", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "725", "name": "Litten", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "726", "name": "Torracat", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "727", "name": "Incineroar", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "728", "name": "Popplio", "hp": "0", "atk": "0", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "729", "name": "Brionne", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "730", "name": "Primarina", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "731", "name": "Pikipek", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "732", "name": "Trumbeak", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "733", "name": "Toucannon", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "734", "name": "Yungoos", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "735", "name": "Gumshoos", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "736", "name": "Grubbin", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "737", "name": "Charjabug", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "738", "name": "Vikavolt", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "739", "name": "Crabrawler", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "740", "name": "Crabominable", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "741", "name": "Oricorio", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "742", "name": "Cutiefly", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "743", "name": "Ribombee", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "744", "name": "Rockruff", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "745", "name": "Lycanroc", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "746", "name": "Wishiwashi (Solo Form)", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "746Sc", "name": "Wishiwashi (School Form)", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "747", "name": "Mareanie", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "748", "name": "Toxapex", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "749", "name": "Mudbray", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "750", "name": "Mudsdale", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "751", "name": "Dewpider", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "752", "name": "Araquanid", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "753", "name": "Fomantis", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "754", "name": "Lurantis", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "755", "name": "Morelull", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "756", "name": "Shiinotic", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "757", "name": "Salandit", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "758", "name": "Salazzle", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "759", "name": "Stufful", "hp": "0", "atk": "1", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "760", "name": "Bewear", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "761", "name": "Bounsweet", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "762", "name": "Steenee", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "2"},
	{"id": "763", "name": "Tsareena", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "764", "name": "Comfey", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "765", "name": "Oranguru", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "766", "name": "Passimian", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "767", "name": "Wimpod", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "768", "name": "Golisopod", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "769", "name": "Sandygast", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "770", "name": "Palossand", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "771", "name": "Pyukumuku", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "772", "name": "Type: Null", "hp": "2", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "773", "name": "Silvally", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "774", "name": "Minior (Meteor Form)", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "774R", "name": "Minior (Red Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "774O", "name": "Minior (Orange Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "774Y", "name": "Minior (Yellow Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "774G", "name": "Minior (Green Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "774B", "name": "Minior (Blue Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "774I", "name": "Minior (Indigo Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "774V", "name": "Minior (Violet Core)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "775", "name": "Komala", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "776", "name": "Turtonator", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "777", "name": "Togedemaru", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "778", "name": "Mimikyu", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "2", "spe": "0"},
	{"id": "779", "name": "Bruxish", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "780", "name": "Drampa", "hp": "0", "atk": "0", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "781", "name": "Dhelmise", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "782", "name": "Jangmo-o", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "783", "name": "Hakamo-o", "hp": "0", "atk": "0", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "784", "name": "Kommo-o", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "785", "name": "Tapu Koko", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "786", "name": "Tapu Lele", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "787", "name": "Tapu Bulu", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "788", "name": "Tapu Fini", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "789", "name": "Cosmog", "hp": "1", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "790", "name": "Cosmoem", "hp": "0", "atk": "0", "def": "1", "spa": "0", "spd": "1", "spe": "0"},
	{"id": "791", "name": "Solgaleo", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "792", "name": "Lunala", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "793", "name": "Nihilego", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "3", "spe": "0"},
	{"id": "794", "name": "Buzzwole", "hp": "0", "atk": "1", "def": "2", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "795", "name": "Pheromosa", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"},
	{"id": "796", "name": "Xurkitree", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "797", "name": "Celesteela", "hp": "0", "atk": "1", "def": "1", "spa": "1", "spd": "0", "spe": "0"},
	{"id": "798", "name": "Kartana", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "799", "name": "Guzzlord", "hp": "3", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "800", "name": "Necrozma", "hp": "0", "atk": "1", "def": "0", "spa": "2", "spd": "0", "spe": "0"},
	{"id": "800DM", "name": "Necrozma (Dusk Mane)", "hp": "0", "atk": "3", "def": "0", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "800DW", "name": "Necrozma (Dawn Wings)", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "800U", "name": "Necrozma (Ultra Necrozma)", "hp": "0", "atk": "1", "def": "0", "spa": "1", "spd": "0", "spe": "1"},
	{"id": "801", "name": "Magearna", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "802", "name": "Marshadow", "hp": "0", "atk": "2", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "803", "name": "Poipole", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "1"},
	{"id": "804", "name": "Naganadel", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "805", "name": "Stakataka", "hp": "0", "atk": "0", "def": "3", "spa": "0", "spd": "0", "spe": "0"},
	{"id": "806", "name": "Blacephalon", "hp": "0", "atk": "0", "def": "0", "spa": "3", "spd": "0", "spe": "0"},
	{"id": "807", "name": "Zeraora", "hp": "0", "atk": "0", "def": "0", "spa": "0", "spd": "0", "spe": "3"}
]